export const householdServices = [
    { id: 1, name: 'Barber', image: 'https://www.shutterstock.com/image-vector/barber-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 2, name: 'Electrician', image: 'https://www.shutterstock.com/image-vector/electrician-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 3, name: 'Carpenter', image: 'https://www.shutterstock.com/image-vector/carpenter-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 4, name: 'Gardener', image: 'https://www.shutterstock.com/image-vector/gardener-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 5, name: 'Plumber', image: 'https://www.shutterstock.com/image-vector/plumber-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 6, name: 'Cleaner', image: 'https://www.shutterstock.com/image-vector/cleaner-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 7, name: 'Painter', image: 'https://www.shutterstock.com/image-vector/painter-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 8, name: 'Mechanic', image: 'https://www.shutterstock.com/image-vector/mechanic-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 9, name: 'Cook', image: 'https://www.shutterstock.com/image-vector/cook-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 10, name: 'Driver', image: 'https://www.shutterstock.com/image-vector/driver-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 11, name: 'Tutor', image: 'https://www.shutterstock.com/image-vector/tutor-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 12, name: 'Maid', image: 'https://www.shutterstock.com/image-vector/maid-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 13, name: 'Babysitter', image: 'https://www.shutterstock.com/image-vector/babysitter-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 14, name: 'Laundry', image: 'https://www.shutterstock.com/image-vector/laundry-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 15, name: 'Pest Control', image: 'https://www.shutterstock.com/image-vector/pest-control-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 16, name: 'AC Repair', image: 'https://www.shutterstock.com/image-vector/ac-repair-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 17, name: 'Fitness Trainer', image: 'https://www.shutterstock.com/image-vector/fitness-trainer-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 18, name: 'Yoga Instructor', image: 'https://www.shutterstock.com/image-vector/yoga-instructor-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 19, name: 'Massage', image: 'https://www.shutterstock.com/image-vector/massage-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 20, name: 'Pet Care', image: 'https://www.shutterstock.com/image-vector/pet-care-vector-icon-illustration-isolated-260nw-345062690.jpg' },
  ];

  export const travelServices = [
    { id: 1, name: 'Ticket Booking', image: 'https://www.shutterstock.com/image-vector/ticket-booking-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 2, name: 'Guide', image: 'https://www.shutterstock.com/image-vector/guide-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 3, name: 'Hotel Booking', image: 'https://www.shutterstock.com/image-vector/hotel-booking-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 4, name: 'Car Rental', image: 'https://www.shutterstock.com/image-vector/car-rental-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 5, name: 'Travel Insurance', image: 'https://www.shutterstock.com/image-vector/travel-insurance-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 6, name: 'Tour Packages', image: 'https://www.shutterstock.com/image-vector/tour-packages-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 7, name: 'Visa Assistance', image: 'https://www.shutterstock.com/image-vector/visa-assistance-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 8, name: 'Forex Services', image: 'https://www.shutterstock.com/image-vector/forex-services-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 9, name: 'Cruise Booking', image: 'https://www.shutterstock.com/image-vector/cruise-booking-vector-icon-illustration-isolated-260nw-345062690.jpg' },
    { id: 10, name: 'Travel Accessories', image: 'https://www.shutterstock.com/image-vector/travel-accessories-vector-icon-illustration-isolated-260nw-345062690.jpg' },
  ];